# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            position.stack.client:
                scope: 'http://api\.positionstack\.com/v1/'
                base_uri: 'http://api.positionstack.com/v1/'
            open.weather.client:
                scope: 'https://api\.openweathermap\.org/data/2.5/'
                base_uri: 'https://api.openweathermap.org/data/2.5/'
            ambee.data.client:
                scope: 'https://api\.ambeedata\.com/'
                base_uri: 'https://api.ambeedata.com/'
                headers:
                    x-api-key: '%env(AMBEEDATA_API_KEY)%'
                    Content-type: "application/json"

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
