version: '3'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: weather_app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/weather_app
    depends_on:
      - database
    command: bash -c "composer install && php bin/console --no-interaction doctrine:migrations:migrate && php-fpm"
    tty: true
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/weather_app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - '6378:6379'
  node:
    container_name: node
    image: node:14.21.1-alpine
    volumes:
      - .:/var/www/weather_app
    command: sh -c "cd /var/www/weather_app && npm install --save-dev && npm run build"
    tty: true